FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean install -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/bank-account-core/target/*.jar ./bank-account-core.jar
EXPOSE 11056
ENTRYPOINT ["java", "-jar", "bank-account-core.jar"]